# Generated by Django 2.2.2 on 2019-06-22 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miniblog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bloginstance',
            old_name='imprint',
            new_name='blog_title',
        ),
    ]
