# Generated by Django 2.2.2 on 2019-06-22 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miniblog', '0002_auto_20190622_0216'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloginstance',
            name='blogger',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='miniblog.Blogger'),
        ),
    ]
