# Generated by Django 2.2.2 on 2019-06-22 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniblog', '0003_bloginstance_blogger'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogReader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('profile_description', models.CharField(help_text='Tell us about yourself', max_length=1000, null=True)),
            ],
            options={
                'ordering': ['user_name'],
            },
        ),
    ]
