# Generated by Django 2.2.2 on 2019-06-22 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniblog', '0006_auto_20190622_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloginstance',
            name='id',
            field=models.UUIDField(default=models.CharField(max_length=200), help_text='Unique ID for this particular blog entry across whole blog', primary_key=True, serialize=False),
        ),
    ]
