# Generated by Django 2.2.2 on 2019-06-23 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miniblog', '0008_auto_20190622_1936'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bloginstance',
            options={'ordering': ['-blog_entry_date']},
        ),
    ]
